# Generated by Django 4.0.4 on 2022-05-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_user_alter_services_options_alter_services_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Сотрудник'),
        ),
    ]
