# Generated by Django 4.0.4 on 2022-05-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_employee_options_employee_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(to='pages.services'),
        ),
    ]
