# Generated by Django 4.0.4 on 2022-05-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='time_record',
        ),
        migrations.AlterField(
            model_name='record',
            name='date_record',
            field=models.DateTimeField(),
        ),
    ]
