# Generated by Django 4.0.4 on 2022-05-27 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0010_remove_record_time_record_alter_record_date_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'записи', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='record',
            name='date_record',
            field=models.DateTimeField(verbose_name='Дата и время записи'),
        ),
        migrations.AlterField(
            model_name='record',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.employee', verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='record',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.services', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
